---
version: "3.8"
services:
  force:
{% include 'templates/docker-compose-service.yml.j2' %}
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://force-redis:6379/0
      - PORT=5000
      - S3_KEY
      - S3_SECRET
      - DEPLOY_ENV
    env_file: ../.env
    ports:
      - 5000:5000
  force-redis:
    image: redis:3.2-alpine
    ports:
      - 6379:6379
